name: Build kernel packages

on:
  push:
    branches:
       - 'fpga-ofs-dev'
       - 'fpga-ofs-dev-*-lts'
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
       - 'fpga-ofs-dev'
       - 'fpga-ofs-dev-*-lts'
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yml'

  workflow_dispatch:

jobs:
  build:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    uses: intel-innersource/applications.fpga.opae.linux-dfl/.github/workflows/build.yml@main
